theme: jekyll-theme-cayman
title: Welcome to Uma's homepage!
description: Currently a high school Math teacher, learned and certified in data analytics. With strong background in Math and Statistics,looking for a junior analyst position where I can constantly learn about new skills and technologies.
